version: '3.8'

services:
  app:
    image: 'ghcr.io/roboticsoutreach/uffd:2.3.1'
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - 'uffd_instance:/uffd/instance'
      - 'data:/data'
    networks:
      - uffd_default
      - nginx-proxy-manager_default

volumes:
  uffd_instance:
  data:
